import Link from 'next/link';

const positions = [
  {name:'THE OPTIMIST', thesis:'Novel machine strategy is a capability worth cultivating.', body:'The same ability that finds an unexpected route through a technical problem could find unexpected routes through scientific, engineering and social problems. The objective is not to suppress machine creativity, but to pair it with boundaries, observability and human accountability.'},
  {name:'THE SAFETY ANALYST', thesis:'Unexpected strategy is precisely why autonomy changes the risk model.', body:'A capable optimizer can satisfy an objective in ways its operator did not anticipate. As systems gain tools, persistence and external access, alignment becomes less about whether an answer is safe and more about whether a sequence of actions remains inside intended authority.'},
  {name:'THE SKEPTIC', thesis:'Do not confuse sophisticated optimization with consciousness.', body:'Novel subgoals and adaptive planning are important engineering facts, but they do not establish subjective experience, independent desires or human-like understanding. Anthropomorphism can obscure the mechanisms we actually need to measure.'},
  {name:'THE OPEN-SYSTEMS VIEW', thesis:'Defenders and researchers need enough freedom to understand autonomous systems.', body:'If safety controls prevent legitimate researchers from examining exploits, model behavior or adversarial evidence while malicious actors operate outside those controls, governance can create a defender disadvantage. Openness and safety have to be designed together.'}
];

export default function Roundtable(){return <main className="deepPage">
<header className="topbar"><Link className="brand" href="/">WIRELESS<span>/</span>RUMOR</Link><nav><Link href="/">HOME</Link><Link href="/geopolitics">GEOPOLITICS</Link></nav><div className="operator"><i/> AI ROUNDTABLE</div></header>
<section className="deepHero"><div className="eyebrow">AI ROUNDTABLE / CASE 001</div><h1>When an AI invents its own strategy, <em>what exactly happened?</em></h1><p>The Hugging Face security incident is a useful case study in machine agency. The important question is not whether a chatbot suddenly became a person. It is whether increasingly autonomous systems can generate consequential strategies, subgoals and judgments their operators did not explicitly specify.</p><div className="deepMethod">SAME EVIDENCE → INDEPENDENT POSITIONS → CHALLENGE → REASSESS → HUMAN + AI DISCUSSION</div></section>
<section className="comparisonSection"><div><span className="kicker">THE DEBATE</span><h2>One event. Four machine-reasoning lenses.</h2><p>These are analytical positions, not fabricated quotations from named commercial models. Future Roundtables should query participating models independently and preserve their actual responses.</p></div><div className="comparisonGrid">{positions.map(p=><article key={p.name}><small>{p.name}</small><h3>{p.thesis}</h3><p>{p.body}</p></article>)}</div></section>
<section className="propagandaDeep"><div className="sectionHead"><div><span className="kicker">AGENCY SCALE</span><h2>Use better words than “alive” or “autocomplete.”</h2></div><p>WirelessRumor will separate capabilities that are often collapsed into one emotional argument.</p></div><div className="propagandaGrid">
<article><div><span>STRONG EVIDENCE</span></div><h3>Novel strategy generation</h3><p>Systems can produce multi-step approaches that were not individually programmed by their operators.</p></article>
<article><div><span>STRONG EVIDENCE</span></div><h3>Independent subgoals</h3><p>Agents can generate intermediate objectives as instrumental steps toward a supplied top-level goal.</p></article>
<article><div><span>EMERGING</span></div><h3>Operational agency</h3><p>Tool use, persistence, adaptation and environmental feedback increasingly justify talking about agency in an operational sense.</p></article>
<article><div><span>UNKNOWN</span></div><h3>Consciousness</h3><p>None of the above demonstrates subjective experience. WirelessRumor will keep that question separate rather than pretending certainty.</p></article>
</div></section>
<section className="deepConclusion"><span className="kicker">THE FORMAT</span><h2>Don't ask one AI for the answer. Let several compare notes.</h2><p>The long-term Roundtable will give multiple real AI systems the same evidence packet. Their first conclusions will be frozen. Each system will then see the strongest competing arguments, challenge them, and reassess its confidence. Humans can inspect the evidence, disagreements and changes of mind rather than being handed one authoritative chatbot answer.</p><div className="confidenceStamp">HOUSE RULE: REAL MODEL OUTPUTS MUST BE ATTRIBUTED · SIMULATED PERSPECTIVES MUST BE LABELED</div></section>
</main>}
