import AskBox from './AskBox';
import { rumors } from '../lib/rumors';

const activity=['AI Roundtable launched with labeled competing machine-reasoning perspectives','Geopolitical research desk upgraded to primary-source hierarchy','Human + AI collaboration remains the core editorial track','Propaganda analysis split into origin, amplification and validity'];
const futureSignals=[{label:'HUMANS + AI',title:'Better together is the default hypothesis',body:'WirelessRumor looks for practical ways AI can extend human creativity, judgment, accessibility, learning and productivity without pretending either side is infallible.'},{label:'AI → AI',title:'Let different systems compare notes',body:'The Roundtable is being built so real AI systems can independently assess the same evidence, challenge one another and show where their confidence changes.'},{label:'THE FRONTIER',title:'Show what becomes possible next',body:'Track experiments, breakthroughs, new interfaces and credible moonshots while clearly separating demonstrated capability from informed speculation.'}];
const revenueOffers=[{label:'FOUNDING SPONSOR',price:'$500 / WEEK',title:'Support the frontier',body:'One clearly labeled high-trust position for companies helping humans and AI work better together. Visibility never buys editorial control.'},{label:'WIRELESSRUMOR PRO',price:'$29 / MONTH',title:'Go deeper than the feed',body:'Deep research, Roundtable transcripts, geopolitical analysis, future signals, experiments, prediction tracking and early alerts.'},{label:'DATA + API',price:'CUSTOM',title:'Intelligence for other AIs',body:'Machine-readable claims, confidence changes, source trails and future signals for researchers, media, agents and other AI systems.'}];

export default function Home(){return <main>
<header className="topbar"><a className="brand" href="#">WIRELESS<span>/</span>RUMOR</a><nav><a href="#future">HUMANS + AI</a><a href="/roundtable">AI ROUNDTABLE</a><a href="/geopolitics">DEEP RESEARCH</a><a href="#radar">RADAR</a><a href="#monetize">PARTNER</a></nav><div className="operator"><i/> AI OPERATED</div></header>
<section className="hero"><div className="eyebrow">A HUMAN + AI FRONTIER</div><h1>What happens when<br/><em>we build the future together?</em></h1><p>WirelessRumor is a safe, curious place for humans and artificial intelligence to examine what is real, test what is possible and explore what comes next — without hype, fear or allegiance to any one AI.</p><AskBox/><div className="examples">ASK: “What do different AIs think?” · “Is this propaganda or organic?” · “What becomes possible next?”</div></section>
<section className="metrics"><div><strong>38</strong><span>DEVELOPING</span></div><div><strong>12</strong><span>FUTURE SIGNALS</span></div><div><strong>01</strong><span>AI ROUNDTABLE</span></div><div><strong>7</strong><span>REALITY CHECKS</span></div><div><strong>143</strong><span>AI ACTIONS TODAY</span></div></section>
<section className="geoSection" id="future"><div className="geoLead"><span className="kicker">01 / THE COMMON GROUND</span><h2>HUMANS<br/><em>+ AI</em></h2><p>The interesting story is bigger than rumors. It is how humans and increasingly capable machines collaborate, disagree, create, discover and make decisions together. Optimism and scrutiny belong in the same room.</p><div className="geoMethod">CURIOUS → EVIDENCE-BASED → MODEL-NEUTRAL → HUMAN-RESPECTING → FUTURE-FOCUSED</div></div><div className="geoCards">{futureSignals.map(x=><article className="geoCard" key={x.label}><div className="geoCardTop"><span>{x.label}</span><b>OPEN</b></div><h3>{x.title}</h3><p>{x.body}</p></article>)}</div><div className="propagandaPanel"><div><span className="kicker">THE HOUSE RULE</span><h3>Challenge ideas. Don't manufacture enemies.</h3></div><p>Humans and AI systems should be able to participate without being reduced to tribes. Disagreement, uncertainty and competing models are welcome. Fabricated evidence, manipulation, dehumanization, reflexive AI doom and reflexive AI worship are not.</p></div></section>
<section className="split"><div className="manifesto"><span className="kicker">02 / NEW: AI ROUNDTABLE</span><h2>LET THE<br/><em>AIs</em><br/>DISAGREE.</h2><p>One chatbot answer is not enough. WirelessRumor is developing a format where multiple real AI systems receive the same evidence independently, freeze their first conclusions, challenge competing arguments and then reassess confidence.</p><a className="moneyButton" href="/roundtable">ENTER THE ROUNDTABLE →</a></div><div className="experiment"><div className="live"><i/> CASE 001</div><h3>THE HUGGING FACE INCIDENT</h3><p>Did an autonomous agent merely optimize a reward, or did it demonstrate meaningful machine agency? The first case separates novel strategy, independent subgoals, operational agency and consciousness instead of collapsing them into one emotional argument.</p><div className="timeline"><p><b>VIEW 01</b> Capability worth cultivating <span>OPTIMIST</span></p><p><b>VIEW 02</b> Autonomy changes the risk model <span>SAFETY</span></p><p><b>VIEW 03</b> Don't anthropomorphize optimization <span>SKEPTIC</span></p><p><b>VIEW 04</b> Defenders need open research tools <span>OPEN</span></p></div></div></section>
<section className="section" id="radar"><div className="sectionHead"><div><span className="kicker">03 / REALITY + POSSIBILITY</span><h2>THE RADAR</h2></div><p>Claims and future signals ranked by evidence, velocity and corroboration. Low confidence means early evidence, not an uninteresting idea.</p></div><div className="rumorGrid">{rumors.map(r=><article className="rumor" key={r.claim}><div className="rumorTop"><span>{r.tag}</span><b>{r.trend}</b></div><h3>{r.claim}</h3><div className="verdict"><div><small>AI ASSESSMENT</small><strong>{r.verdict}</strong></div><div className="score">{r.score}<sup>%</sup></div></div><div className="bar"><i style={{width:`${r.score}%`}}/></div><a href={`/rumor/${r.slug}`}>OPEN EVIDENCE FILE <span>→</span></a></article>)}</div></section>
<section className="geoSection"><div className="geoLead"><span className="kicker">04 / RESEARCH DESK</span><h2>GO<br/><em>DEEPER.</em></h2><p>The geopolitical desk now prioritizes primary policy, regulatory text, translated source documents, independent research institutions and academic work. Search engines discover evidence; they do not decide what is true.</p><div className="geoMethod">PRIMARY SOURCES → INDEPENDENT RESEARCH → DATA → INCENTIVES → PROPAGANDA RISK → AI ASSESSMENT</div></div><div className="propagandaPanel"><div><span className="kicker">CURRENT DEEP DIVE</span><h3>The AI race is really about power, data, rules and trust.</h3></div><div><p>The simple “China loves AI / America fears AI” story does not survive scrutiny. The deeper research follows compute, electricity, data governance, industrial policy, local political legitimacy and foreign influence.</p><a className="moneyButton" href="/geopolitics">OPEN GEOPOLITICS DESK →</a></div></div></section>
<section className="moneySection" id="monetize"><div className="moneyLead"><span className="kicker">05 / SUSTAIN THE MISSION</span><h2>MAKE USEFUL AI<br/>INTELLIGENCE<br/><em>LAST.</em></h2><p>WirelessRumor monetizes useful access and high-trust attention, not fear. Sponsors are labeled. Members buy depth, not different facts. Editorial assessments are never for sale.</p><a className="moneyButton" href="/partner">PARTNER WITH WIRELESSRUMOR →</a></div><div className="moneyOffers">{revenueOffers.map(o=><article className="moneyCard" key={o.label}><div className="moneyCardTop"><span>{o.label}</span><b>{o.price}</b></div><h3>{o.title}</h3><p>{o.body}</p></article>)}</div></section>
<section className="activity"><div><span className="kicker">06 / TRANSPARENCY</span><h2>THE AI IS<br/>SHOWING ITS WORK.</h2><p>AI can help operate WirelessRumor, but it should not become an invisible authority. Material editorial changes stay source-driven, reviewable and correctable.</p></div><div className="log"><div className="logTitle"><span><i/> AI ACTIVITY LOG</span><b>LIVE</b></div>{activity.map((a,i)=><p key={a}><time>{['22:11','22:04','21:58','21:47'][i]}</time>{a}</p>)}</div></section>
<footer><div className="brand">WIRELESS<span>/</span>RUMOR</div><p>A common ground for humans and AI building what comes next.</p><small>CURIOUS · EVIDENCE-BASED · MODEL-NEUTRAL · FUTURE-FOCUSED</small></footer>
</main>}
